/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author osboxes
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneMain = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jCorpusMenu = new javax.swing.JMenu();
        jMenuItemCreateCorpus = new javax.swing.JMenuItem();
        jMenuItemAvailableCorporaReport = new javax.swing.JMenuItem();
        jMenuAnalyzer = new javax.swing.JMenu();
        jMenuExtractEntities = new javax.swing.JMenuItem();
        jMenuItemReviewEntities = new javax.swing.JMenuItem();
        jMenuEntitiesNormalization = new javax.swing.JMenuItem();
        jMenuReviewFixNormalization = new javax.swing.JMenu();
        jMenuIGenerateNewClusterByHand = new javax.swing.JMenuItem();
        jMenuMoveEntitiesBetweenClusters = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemGenerateCanonicalEntities = new javax.swing.JMenuItem();
        jMenuRelateNormalEntitiesSentence = new javax.swing.JMenuItem();
        jMenuItemUpdateRolesForNormalizedEntities = new javax.swing.JMenuItem();
        jMenuCoOcurrenceParagraph = new javax.swing.JMenu();
        jMenuCoOcurrenceSentence = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemGenerateFilesForGephi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCorpusMenu.setText("Corpus");

        jMenuItemCreateCorpus.setText("Create corpus");
        jMenuItemCreateCorpus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateCorpusActionPerformed(evt);
            }
        });
        jCorpusMenu.add(jMenuItemCreateCorpus);

        jMenuItemAvailableCorporaReport.setText("Available corpora report");
        jMenuItemAvailableCorporaReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAvailableCorporaReportActionPerformed(evt);
            }
        });
        jCorpusMenu.add(jMenuItemAvailableCorporaReport);

        menuBar.add(jCorpusMenu);

        jMenuAnalyzer.setText("Analyzer");

        jMenuExtractEntities.setText("Extract entities");
        jMenuExtractEntities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExtractEntitiesActionPerformed(evt);
            }
        });
        jMenuAnalyzer.add(jMenuExtractEntities);

        jMenuItemReviewEntities.setText("Review and fix entities");
        jMenuItemReviewEntities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReviewEntitiesActionPerformed(evt);
            }
        });
        jMenuAnalyzer.add(jMenuItemReviewEntities);

        jMenuEntitiesNormalization.setText("Entities clustering");
        jMenuEntitiesNormalization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEntitiesNormalizationActionPerformed(evt);
            }
        });
        jMenuAnalyzer.add(jMenuEntitiesNormalization);

        jMenuReviewFixNormalization.setText("Review and fix clustering");

        jMenuIGenerateNewClusterByHand.setText("Generate new clusters by hand");
        jMenuIGenerateNewClusterByHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIGenerateNewClusterByHandActionPerformed(evt);
            }
        });
        jMenuReviewFixNormalization.add(jMenuIGenerateNewClusterByHand);

        jMenuMoveEntitiesBetweenClusters.setText("Move entities between clusters");
        jMenuMoveEntitiesBetweenClusters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMoveEntitiesBetweenClustersActionPerformed(evt);
            }
        });
        jMenuReviewFixNormalization.add(jMenuMoveEntitiesBetweenClusters);

        jMenuAnalyzer.add(jMenuReviewFixNormalization);

        jMenu1.setText("Entities normalization");

        jMenuItemGenerateCanonicalEntities.setText("Generate normalized entities");
        jMenuItemGenerateCanonicalEntities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerateCanonicalEntitiesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemGenerateCanonicalEntities);

        jMenuRelateNormalEntitiesSentence.setText("Relate nomalized entities to sentences");
        jMenuRelateNormalEntitiesSentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelateNormalEntitiesSentenceActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuRelateNormalEntitiesSentence);

        jMenuItemUpdateRolesForNormalizedEntities.setText("Update roles for normalized entities");
        jMenuItemUpdateRolesForNormalizedEntities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateRolesForNormalizedEntitiesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUpdateRolesForNormalizedEntities);

        jMenuAnalyzer.add(jMenu1);

        jMenuCoOcurrenceParagraph.setText("Generate social network");

        jMenuCoOcurrenceSentence.setText("Co-ocurrence at paragraph level");
        jMenuCoOcurrenceSentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCoOcurrenceSentenceActionPerformed(evt);
            }
        });
        jMenuCoOcurrenceParagraph.add(jMenuCoOcurrenceSentence);

        jMenuItem3.setText("Co-ocurrence at sentence level");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuCoOcurrenceParagraph.add(jMenuItem3);

        jMenuAnalyzer.add(jMenuCoOcurrenceParagraph);

        jMenuItemGenerateFilesForGephi.setText("Generate files for Gephi");
        jMenuItemGenerateFilesForGephi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerateFilesForGephiActionPerformed(evt);
            }
        });
        jMenuAnalyzer.add(jMenuItemGenerateFilesForGephi);

        menuBar.add(jMenuAnalyzer);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCreateCorpusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateCorpusActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new GenerationOfCorpus();
        jDesktopPaneMain.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItemCreateCorpusActionPerformed

    private void jMenuExtractEntitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExtractEntitiesActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new EntitiesExtraction();
        jDesktopPaneMain.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_jMenuExtractEntitiesActionPerformed

    private void jMenuItemAvailableCorporaReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAvailableCorporaReportActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new CorpusDocumentsReport();
        jDesktopPaneMain.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItemAvailableCorporaReportActionPerformed

    private void jMenuItemReviewEntitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReviewEntitiesActionPerformed
        // TODO add your handling code here:
        //javax.swing.JInternalFrame s = new EntititesRevisionAndCorrection();
        javax.swing.JInternalFrame s = new EntititesRevisionAndFixing();
        jDesktopPaneMain.add(s);
        s.setVisible(true);        
    }//GEN-LAST:event_jMenuItemReviewEntitiesActionPerformed

    private void jMenuEntitiesNormalizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEntitiesNormalizationActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new ClustersExtraction();
        jDesktopPaneMain.add(s);
        s.setVisible(true);   
    }//GEN-LAST:event_jMenuEntitiesNormalizationActionPerformed

    private void jMenuIGenerateNewClusterByHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIGenerateNewClusterByHandActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new GeneratingNewClustersByHand();
        jDesktopPaneMain.add(s);
        s.setVisible(true); 
    }//GEN-LAST:event_jMenuIGenerateNewClusterByHandActionPerformed

    private void jMenuMoveEntitiesBetweenClustersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMoveEntitiesBetweenClustersActionPerformed
        // TODO add your handling code here:        
        javax.swing.JInternalFrame s = new MovingEntitiesBetweenClusters();
        jDesktopPaneMain.add(s);
        s.setVisible(true);                 
    }//GEN-LAST:event_jMenuMoveEntitiesBetweenClustersActionPerformed

    private void jMenuItemGenerateCanonicalEntitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerateCanonicalEntitiesActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new GeneratingNormalizedEntities();
        jDesktopPaneMain.add(s);
        s.setVisible(true); 
    }//GEN-LAST:event_jMenuItemGenerateCanonicalEntitiesActionPerformed

    private void jMenuRelateNormalEntitiesSentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelateNormalEntitiesSentenceActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new GenerateRelationNormEntitiesSentences();
        jDesktopPaneMain.add(s);
        s.setVisible(true);         
    }//GEN-LAST:event_jMenuRelateNormalEntitiesSentenceActionPerformed

    private void jMenuItemUpdateRolesForNormalizedEntitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateRolesForNormalizedEntitiesActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new CreatingRolesForNormalizedEntities();
        jDesktopPaneMain.add(s);
        s.setVisible(true);                 
        
    }//GEN-LAST:event_jMenuItemUpdateRolesForNormalizedEntitiesActionPerformed

    private void jMenuItemGenerateFilesForGephiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerateFilesForGephiActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new GenerateGephiFiles();
        jDesktopPaneMain.add(s);
        s.setVisible(true);         
    }//GEN-LAST:event_jMenuItemGenerateFilesForGephiActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new GenerateASocialNetworkCoOcurrenceSentence();
        jDesktopPaneMain.add(s);
        s.setVisible(true);         
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuCoOcurrenceSentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCoOcurrenceSentenceActionPerformed
        // TODO add your handling code here:
        javax.swing.JInternalFrame s = new GenerateASocialNetworkCoOcurrenceParagraph();
        jDesktopPaneMain.add(s);
        s.setVisible(true);          
    }//GEN-LAST:event_jMenuCoOcurrenceSentenceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCorpusMenu;
    private javax.swing.JDesktopPane jDesktopPaneMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAnalyzer;
    private javax.swing.JMenu jMenuCoOcurrenceParagraph;
    private javax.swing.JMenuItem jMenuCoOcurrenceSentence;
    private javax.swing.JMenuItem jMenuEntitiesNormalization;
    private javax.swing.JMenuItem jMenuExtractEntities;
    private javax.swing.JMenuItem jMenuIGenerateNewClusterByHand;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAvailableCorporaReport;
    private javax.swing.JMenuItem jMenuItemCreateCorpus;
    private javax.swing.JMenuItem jMenuItemGenerateCanonicalEntities;
    private javax.swing.JMenuItem jMenuItemGenerateFilesForGephi;
    private javax.swing.JMenuItem jMenuItemReviewEntities;
    private javax.swing.JMenuItem jMenuItemUpdateRolesForNormalizedEntities;
    private javax.swing.JMenuItem jMenuMoveEntitiesBetweenClusters;
    private javax.swing.JMenuItem jMenuRelateNormalEntitiesSentence;
    private javax.swing.JMenu jMenuReviewFixNormalization;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
